### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by josueBarretogit** [josueBarretogit/goApiBookstore#12]
- [x] get list of genres
- [x] filter books by genre and bestSellers 
- [x] Get best book sellers, the most selled 
- [x] Upload book cover image
- [x] Filter books by language
- [x] List reviews asociated to book paginated
- [x] Upload user´s profile picture
- [x] Follow api design best practices
- [x] List books formats
- [x]  Filter books by release date
- [ ] Filter by most reviewed
- [x] Combine filters
- [x] Get number of reviews and percentage per star of a book, get average rating, and relation between ratings

**Comment by josueBarretogit** [comment]
In order to search a book 

get : 
- [x] book title,
- [x]  book authors name and lastname , 
- [x]  book publication date, 
- [x] books format price,
- [x] book rating, 
- [x] book cover url

the filter should: 

- [x] filter by genre
- [x] filter by range of prices
- [x] sort by low price to high, high price to low
- [x] filter by rating
- [x] filter by languages
- [x] filter by authors name
- [x] filter by release date, get from a date and to a date or in between
- [x] filter by books title
- [x] Supports pagination and amount of items per page
- [x] can combine filters

**Comment by josueBarretogit** [comment]
- [x] create an endpoint that gets a book with only the data required
`books/one/:id` and get the average rating

- [x] get extra book details (depending on book format)

**Comment by josueBarretogit** [comment]
- [x] Get the reviews of a customer, get: review id review rating, review title, review body. book coverphoto, book id
- [x] Get Authors books: book coverphotourl, book title, book avg rating, formats: price
